feat: add ReactDemo
SrujanaGajagouni/SrujanaGajagouni_ldp pull request #14
Opened 2024-07-11 17:13 UTC by SrujanaGajagouni

### Applied external styling followed atomic design structure.
![image](https://github.com/SrujanaGajagouni/SrujanaGajagouni_ldp/assets/170396722/e64dabbe-1c0d-4a4d-a35f-eee961e25d06)

2024-07-12 11:09 UTC, saicharan-zemoso requested changes
resolve all comments

2024-07-12 11:09 UTC, saicharan-zemoso commented on ReactDemo/my-react/public/assets/bike.svg
keep svgs under public/assets/icons

2024-07-12 11:09 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/atoms/Image/index.tsx
> +}
rename it to Image if the folder name is Image

2024-07-12 11:09 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/atoms/Typography/index.tsx
> +}
rename it to Typography

2024-07-12 11:09 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/atoms/Typography/index.tsx
> +import {Typography, TypographyProps} from '@mui/material'
```suggestion
import {Typography as MuiTypography, TypographyProps} from '@mui/material'
```

2024-07-12 11:09 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/molecules/FooterImage/index.tsx
> +});
keep theme in a separate file in a theme folder

2024-07-12 11:09 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/organism/Main/index.tsx
> +const theme = createTheme({
no need of multiple themes

2024-07-12 11:09 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/organism/Main/index.tsx
> +        </ThemeProvider>
wrap the whole app in Theme provider instead of doing it for each component

2024-07-12 11:09 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/organism/Main/index.tsx
> +const Main: React.FC = () => {
provide a name which is more suitable.

2024-07-14 10:21 UTC, SrujanaGajagouni commented
> resolve all comments

Resolved all the comments.

2024-07-15 06:25 UTC, saicharan-zemoso requested changes
resolve all changes

2024-07-15 06:25 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/molecules/FooterImage/index.tsx
> +import train from '../../../../public/assets/icons/train.svg';
don't import svgs as modules change it

2024-07-15 06:25 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/organism/HpCard/index.tsx
> +import more from '../../../../public/assets/icons/more.svg';
Same here

2024-07-15 06:25 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/organism/HpCard/index.tsx
> +export default HpCard;
rename this component and provide more suitable name like DescriptionCard

2024-07-15 06:25 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/molecules/FooterImage/index.tsx
> +export default ImageCard;
rename it to CommuteRoutes

2024-07-15 06:58 UTC, SrujanaGajagouni commented
> resolve all changes

resolved the changes

2024-07-16 16:28 UTC, saicharan-zemoso requested changes
check if font  family is applied an provide the new screenshot of the componenet

2024-07-16 16:28 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/molecules/CommuteRoutes/index.tsx
> +import '../../../../public/assets/icons/train.svg';
these imports are not required

2024-07-16 16:28 UTC, saicharan-zemoso commented on ReactDemo/my-react/src/components/organism/DescriptionCard/index.tsx
> +import '../../../../public/assets/icons/more.svg';
remove these imports

2024-07-17 06:50 UTC, SrujanaGajagouni commented on ReactDemo/my-react/src/components/organism/DescriptionCard/index.tsx
> +import '../../../../public/assets/icons/more.svg';
> remove these imports

removed image imports

2024-07-17 08:38 UTC, saicharan-zemoso reviewed
can you provide the screenshot of the updated component

2024-07-17 09:47 UTC, SrujanaGajagouni commented
> can you provide the screenshot of the updated component

Attached updated screenshot.

2024-07-17 10:46 UTC, saicharan-zemoso approved these changes
looks good to me!

2024-07-17 10:50 UTC, merged